package com.il.util.ui.tabs.drt;

import com.il.util.dto.FileInfo;
import com.il.util.setvices.DropDuplicatesService;
import com.il.util.setvices.UIService;
import com.il.util.setvices.Util;
import com.il.util.ui.components.ProgressWindowWrap;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.List;
import java.util.Locale;

@Component
@Scope(BeanDefinition.SCOPE_SINGLETON)
public class DuplicatesRemoverTabWrap {
    @Autowired
    private DropDuplicatesService dropDuplicatesService;
    @Autowired
    private ProgressWindowWrap progressWindow;
    @Autowired
    private UIService uiService;

    private JPanel root;
    private JScrollPane sc;
    private JTextField tfPath;
    private JButton btnChoose;
    private JButton btnScan;
    private JButton btnDoRemove;
    private JPanel panelResult;
    private JLabel labelMsg;

    @PostConstruct
    private void init() {
        sc.getVerticalScrollBar().setUnitIncrement(16);
        panelResult.setLayout(new BoxLayout(panelResult, BoxLayout.Y_AXIS));
        progressWindow.setIndeterminate();

        btnChoose.addActionListener(event -> {
            tfPath.setText(uiService.chooseFolder());
        });
        btnScan.addActionListener(event -> {
            progressWindow.setVisible(true);
            String path = tfPath.getText();
            List<List<FileInfo>> duplicatesList = dropDuplicatesService.deepSearchDuplicates(path);
            for (List<FileInfo> duplicates : duplicatesList) {
                DupRemResListItemWrap dupRemResListItemWrap = new DupRemResListItemWrap();

                java.awt.Component added = dupRemResListItemWrap.getRoot();
                panelResult.add(added);
                dupRemResListItemWrap.init(duplicates, () -> {
                    panelResult.remove(added);
                    panelResult.revalidate();
                    panelResult.repaint();
                });
            }
            long totalToFree = 0;
            for (List<FileInfo> duplicates : duplicatesList) {
                for (int i = duplicates.size() - 1; i >= 1; i--) {
                    FileInfo fileInfo = duplicates.get(i);
                    totalToFree += fileInfo.getSize();
                }
            }
            labelMsg.setText("Total to free space: " + Util.formatNumberWithSpaces(String.valueOf(Util.bytesToMegabytes(totalToFree))) + " MB");
            progressWindow.setVisible(false);
        });
        btnDoRemove.addActionListener(event -> {

        });
    }

    public JPanel getRoot() {
        return root;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(3, 1, new Insets(4, 0, 4, 4), -1, -1));
        sc = new JScrollPane();
        root.add(sc, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        sc.setViewportView(panel1);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelResult = new JPanel();
        panelResult.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panelResult, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        root.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tfPath = new JTextField();
        Font tfPathFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, tfPath.getFont());
        if (tfPathFont != null) tfPath.setFont(tfPathFont);
        panel2.add(tfPath, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnChoose = new JButton();
        Font btnChooseFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, btnChoose.getFont());
        if (btnChooseFont != null) btnChoose.setFont(btnChooseFont);
        btnChoose.setText("Choose");
        panel2.add(btnChoose, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        root.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnScan = new JButton();
        Font btnScanFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, btnScan.getFont());
        if (btnScanFont != null) btnScan.setFont(btnScanFont);
        btnScan.setText("Scan");
        panel3.add(btnScan, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel3.add(spacer3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnDoRemove = new JButton();
        Font btnDoRemoveFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, btnDoRemove.getFont());
        if (btnDoRemoveFont != null) btnDoRemove.setFont(btnDoRemoveFont);
        btnDoRemove.setText("Do Remove");
        panel3.add(btnDoRemove, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelMsg = new JLabel();
        Font labelMsgFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, labelMsg.getFont());
        if (labelMsgFont != null) labelMsg.setFont(labelMsgFont);
        labelMsg.setText("");
        panel3.add(labelMsg, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
