package com.il.util.ui.tabs.drt;

import com.il.util.dto.FileInfo;
import com.il.util.setvices.Util;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Locale;
import java.util.function.Consumer;

public class FileItemWrap {
    private JPanel root;
    private JLabel labelName;
    private JLabel labelSize;
    private JLabel labelBtnPreview;
    private JButton btnDelete;

    private static abstract class SimpleClickAdapter extends MouseAdapter {
        abstract void onClick();
    }

    public void init(FileInfo fileInfo, Consumer<FileInfo> removeCallback) {
        labelName.setText(fileInfo.getPath());
        labelName.setText("<html><a href=''>" + fileInfo.getPath() + "</a></html>");
        labelName.setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelName.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    String path = fileInfo.getPath();
                    File file = new File(path);
                    if (file.exists()) {
                        if (file.isDirectory()) {
                            new ProcessBuilder("explorer.exe", file.getAbsolutePath()).start();
                        } else {
                            new ProcessBuilder("explorer.exe", "/select,", file.getAbsolutePath()).start();
                        }
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });


        labelBtnPreview.setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelBtnPreview.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new File(fileInfo.getPath()).toURI());
                    labelBtnPreview.setForeground(new Color(59, 139, 187));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        labelSize.setText(Util.formatNumberWithSpaces(String.valueOf(Util.bytesToMegabytes(fileInfo.getSize()))) + " MB");

        btnDelete.addActionListener(event -> {
            int result = JOptionPane.showConfirmDialog(root, "Do you Confirm DELETE?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                File fileToDelete = new File(fileInfo.getPath());
                boolean isDeleteComplete = fileToDelete.delete();
                if (isDeleteComplete) {
                    removeCallback.accept(fileInfo);
                    root.setVisible(false);
                }
            }
        });
    }

    public JPanel getRoot() {
        return root;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 5, new Insets(4, 0, 4, 0), -1, -1));
        labelName = new JLabel();
        Font labelNameFont = this.$$$getFont$$$("JetBrains Mono", -1, 12, labelName.getFont());
        if (labelNameFont != null) labelName.setFont(labelNameFont);
        labelName.setText("Label");
        root.add(labelName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        root.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        labelSize = new JLabel();
        Font labelSizeFont = this.$$$getFont$$$("JetBrains Mono", -1, 12, labelSize.getFont());
        if (labelSizeFont != null) labelSize.setFont(labelSizeFont);
        labelSize.setHorizontalAlignment(4);
        labelSize.setHorizontalTextPosition(10);
        labelSize.setText("<size>");
        root.add(labelSize, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(70, -1), null, null, 0, false));
        labelBtnPreview = new JLabel();
        Font labelBtnPreviewFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, labelBtnPreview.getFont());
        if (labelBtnPreviewFont != null) labelBtnPreview.setFont(labelBtnPreviewFont);
        labelBtnPreview.setForeground(new Color(-14069829));
        labelBtnPreview.setText("Preview");
        root.add(labelBtnPreview, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDelete = new JButton();
        Font btnDeleteFont = this.$$$getFont$$$("JetBrains Mono", -1, 14, btnDelete.getFont());
        if (btnDeleteFont != null) btnDelete.setFont(btnDeleteFont);
        btnDelete.setText("Delete");
        root.add(btnDelete, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
